Dev
Major-Project-BE2018SE/polaris_suite_app pull request #1
Opened 2023-05-05 04:03 UTC by Prasiddha777

2023-05-05 06:08 UTC, alsongarbuja requested changes

2023-05-05 06:08 UTC, alsongarbuja commented on lib/resources/components/custom_textfield.dart
Padding thorai bhaxa hai text lekhda suru batai tassera auxa

2023-05-05 06:08 UTC, alsongarbuja commented on lib/view/signup_screen.dart
![Screenshot 2023-05-05 114701](https://user-images.githubusercontent.com/42911859/236387544-a29c85c2-d4dc-4c0b-acf6-1c5ae84f9ff2.png)

yo back arrow na rakhe hunxa hai register mah

2023-05-06 17:22 UTC, alsongarbuja requested changes

2023-05-06 17:22 UTC, alsongarbuja commented on lib/resources/components/custom_textfield.dart
![image](https://user-images.githubusercontent.com/42911859/236638237-e81a48f6-87dd-4346-80f5-756fd178930c.png)

yesto bhayo jhan

2023-05-16 08:03 UTC, alsongarbuja approved these changes

2023-05-16 16:45 UTC, Salipa-Gurung approved these changes

2023-05-16 16:52 UTC, merged